<?php

define('REVISOR', "REVISOR");
define('EDITOR', "EDITOR");
define('AUTOR', "AUTOR");

define('BUSCAR', "BUSCAR");
define('LISTARAUTORES', "LISTARAUTORES");
define('LISTARREVISORES', "LISTARREVISORES");
define('LISTAREDITORES', "LISTAREDITORES");
define('REVISIONESPENDIENTES', "REVISIONESPENDIENTES");
define('REVISIONESPORREVISOR', "REVISIONESPORREVISOR");
define('REVISIONESPORARTICULO', "REVISIONESPORARTICULO");

define('CORREGIR', "CORREGIR");
define('APROBADO', "APROBADO");
define('DENEGADO', "DENEGADO");

?>